# Generated by Django 5.2.4 on 2025-07-10 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CredentialModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform_name', models.CharField(blank=True, max_length=100, null=True)),
                ('credential', models.CharField(blank=True, max_length=100, null=True)),
                ('login_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
