# Generated by Django 5.2.4 on 2025-07-12 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PassApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialmodel',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
