# Generated by Django 5.2.4 on 2025-07-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PassApp', '0002_credentialmodel_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='credentialmodel',
            name='backup_mail_num',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
